# version: '3.8'  # Secrets are only available since 3.1 version of Docker Compose
services:
  orthanc:
    build:
      context: .
      dockerfile: Dockerfile
    image: orthanc_project
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242 # Port for DICOM
      - 8042:8042 # Port for HTTP
    secrets:
      - orthanc.json
secrets:
  orthanc.json:
    file: ./orthanc/orthanc.json