version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.4
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242 # Porta para comunicação DICOM
      - 8042:8042 # Porta para acesso via navegador
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=orthanc
secrets:
  orthanc.json:
    file: orthanc.json